project:
  title: "Example RNA-seq Analysis"
  type: website
  output-dir: ../docs
  render:
    - dge.qmd

website:
  back-to-top-navigation: true
  sidebar:
    style: "floating"
    search: true
    border: true
    contents:
      - text: Home
        href: index.qmd
      - text: DGE
        href: dge.qmd
    tools:
      - icon: github
        href: https://github.com/baerlachlan/example_RNAseq_analysis
  search:
    location: sidebar
    type: overlay

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 5
